In [2]:
import pandas as pd
df = pd.read_csv('..\data\data.csv')
df.head()

,airline,overall,author,review_date,customer_review,aircraft,traveller_type,cabin,route,date_flown,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Turkish Airlines,7.0,Christopher Hackley,8th May 2019,âœ… Trip Verified | London to Izmir via Istanb...,NaN,Business,Economy Class,London to Izmir via Istanbul,May-19,4.0,5.0,4.0,4.0,2.0,4.0,yes
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Turkish Airlines,2.0,Adriana Pisoi,7th May 2019,âœ… Trip Verified | Istanbul to Bucharest. We ...,NaN,Family Leisure,Economy Class,Istanbul to Bucharest,May-19,4.0,1.0,1.0,1.0,1.0,1.0,no
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(131895, 17)

In [4]:
x=16
df=df.dropna(thresh=df.shape[1]-x,axis=0)

In [5]:
df.head()

,airline,overall,author,review_date,customer_review,aircraft,traveller_type,cabin,route,date_flown,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
1,Turkish Airlines,7.0,Christopher Hackley,8th May 2019,âœ… Trip Verified | London to Izmir via Istanb...,NaN,Business,Economy Class,London to Izmir via Istanbul,May-19,4.0,5.0,4.0,4.0,2.0,4.0,yes
3,Turkish Airlines,2.0,Adriana Pisoi,7th May 2019,âœ… Trip Verified | Istanbul to Bucharest. We ...,NaN,Family Leisure,Economy Class,Istanbul to Bucharest,May-19,4.0,1.0,1.0,1.0,1.0,1.0,no
5,Turkish Airlines,3.0,M Galerko,7th May 2019,âœ… Trip Verified | Rome to Prishtina via Ista...,NaN,Business,Economy Class,Rome to Prishtina via Istanbul,May-19,1.0,4.0,1.0,3.0,1.0,2.0,no
7,Turkish Airlines,10.0,Zeshan Shah,6th May 2019,âœ… Trip Verified | Flew on Turkish Airlines I...,A330,Solo Leisure,Economy Class,Washington Dulles to Karachi,April 2019,4.0,5.0,5.0,5.0,5.0,5.0,yes
9,Turkish Airlines,1.0,Pooja Jain,6th May 2019,âœ… Trip Verified | Mumbai to Dublin via Istan...,NaN,Solo Leisure,Economy Class,Mumbai to Dublin via Istanbul,May-19,1.0,1.0,1.0,1.0,1.0,1.0,no

In [6]:
df.drop(['author','review_date', 'aircraft' , 'route','date_flown','customer_review'],axis=1,inplace=True)

In [7]:
df.head()

,airline,overall,traveller_type,cabin,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
1,Turkish Airlines,7.0,Business,Economy Class,4.0,5.0,4.0,4.0,2.0,4.0,yes
3,Turkish Airlines,2.0,Family Leisure,Economy Class,4.0,1.0,1.0,1.0,1.0,1.0,no
5,Turkish Airlines,3.0,Business,Economy Class,1.0,4.0,1.0,3.0,1.0,2.0,no
7,Turkish Airlines,10.0,Solo Leisure,Economy Class,4.0,5.0,5.0,5.0,5.0,5.0,yes
9,Turkish Airlines,1.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,no

In [8]:
df.shape

(65947, 11)

In [9]:
df.index = range(0, len(df))
df.head()

,airline,overall,traveller_type,cabin,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,Turkish Airlines,7.0,Business,Economy Class,4.0,5.0,4.0,4.0,2.0,4.0,yes
1,Turkish Airlines,2.0,Family Leisure,Economy Class,4.0,1.0,1.0,1.0,1.0,1.0,no
2,Turkish Airlines,3.0,Business,Economy Class,1.0,4.0,1.0,3.0,1.0,2.0,no
3,Turkish Airlines,10.0,Solo Leisure,Economy Class,4.0,5.0,5.0,5.0,5.0,5.0,yes
4,Turkish Airlines,1.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,no

In [10]:
df.isnull().sum()

airline                0
overall             1930
traveller_type     26192
cabin               2644
seat_comfort        5266
cabin_service       5232
food_bev           13339
entertainment      21754
ground_service     26589
value_for_money     1972
recommended         1507
dtype: int64

In [11]:
df.dropna(subset=['overall'], inplace=True)
df.dropna(subset=['cabin'], inplace=True)
df.dropna(subset=['seat_comfort'], inplace=True)
df.dropna(subset=['cabin_service'], inplace=True)
df.dropna(subset=['value_for_money'], inplace=True)
df.dropna(subset=['recommended'], inplace=True)

In [14]:
df.shape

(58288, 11)

In [12]:
df.isnull().sum()

airline                0
overall                0
traveller_type     19656
cabin                  0
seat_comfort           0
cabin_service          0
food_bev            7755
entertainment      15906
ground_service     19792
value_for_money        0
recommended            0
dtype: int64

In [13]:
df['food_bev'].fillna(df['food_bev'].mean(), inplace=True)
df['entertainment'].fillna(df['entertainment'].mean(), inplace=True)
df['ground_service'].fillna(df['ground_service'].mean(), inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_13668\1106618963.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['food_bev'].fillna(df['food_bev'].mean(), inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13668\1106618963.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['entertainment'].fillna(df['entertainment'].mean(), inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13668\1106618963.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ground_service'].fillna(df['ground_service'].mean(), inplace=True)

In [ ]:
df['traveller_type'].fillna(method = 'bfill', inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_17300\775410024.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['traveller_type'].fillna(method = 'bfill', inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_17300\775410024.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['traveller_type'].fillna(method = 'bfill', inplace=True)

In [ ]:
df.isnull().sum()

airline             0
overall             0
traveller_type     53
cabin               0
seat_comfort        0
cabin_service       0
food_bev            0
entertainment       0
ground_service      0
value_for_money     0
recommended         0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

airline            0
overall            0
traveller_type     0
cabin              0
seat_comfort       0
cabin_service      0
food_bev           0
entertainment      0
ground_service     0
value_for_money    0
recommended        0
dtype: int64

In [ ]:
# df['customer_review'][0]

In [ ]:
# df['customer_review']

In [ ]:
# import nltk
# import re
# nltk.download('stopwords')
# nltk.download('wordnet')
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer

In [ ]:
# corpus = []
# wnl  = WordNetLemmatizer()

# for sms in list(df.customer_review):
#   message =  re.sub(pattern='[^a-zA-Z]', repl = ' ', string =sms)
#   message =message.lower()
#   words =message.split() # Tokenizer
#   filtered_words  =[word for word in words if word not in set (stopwords.words ('english'))]
#   lemm_words = [wnl.lemmatize (word) for word in filtered_words]
#   message= ' '.join(lemm_words)
#   corpus.append(message)

In [ ]:
# corpus[:3]

In [ ]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# tfidf = TfidfVectorizer(max_features=700)
# vextors = tfidf.fit_transform(corpus).toarray()
# feature_names = tfidf.get_feature_names_out()

In [ ]:
# x = pd.DataFrame(data=vextors, columns=feature_names)

In [ ]:
# x.head()

In [ ]:
# import nltk
# import re
# import pickle

# with open('/content/drive/MyDrive/Colab Notebooks/tfdai_data_new.pkl', 'wb') as f:
#     pickle.dump(tfidf, f)

# print("TF-IDF vectorizer saved to /content/drive/MyDrive/Colab Notebooks/tfdai_data_new.pkl")

In [ ]:
# x.head()

In [ ]:
# df.drop(['customer_review'],axis=1,inplace=True)

In [ ]:
df.head()

,airline,overall,traveller_type,cabin,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,Turkish Airlines,7.0,Business,Economy Class,4.0,5.0,4.0,4.0,2.0,4.0,yes
1,Turkish Airlines,2.0,Family Leisure,Economy Class,4.0,1.0,1.0,1.0,1.0,1.0,no
2,Turkish Airlines,3.0,Business,Economy Class,1.0,4.0,1.0,3.0,1.0,2.0,no
3,Turkish Airlines,10.0,Solo Leisure,Economy Class,4.0,5.0,5.0,5.0,5.0,5.0,yes
4,Turkish Airlines,1.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,no

In [ ]:
df = pd.get_dummies(df, columns=['airline', 'traveller_type', 'cabin'], drop_first=True , dtype=int)

df.head()

,overall,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended,airline_Adria Airways,airline_Aegean Airlines,...,airline_Wizz Air,airline_airBaltic,airline_easyJet,airline_flydubai,traveller_type_Couple Leisure,traveller_type_Family Leisure,traveller_type_Solo Leisure,cabin_Economy Class,cabin_First Class,cabin_Premium Economy
0,7.0,4.0,5.0,4.0,4.0,2.0,4.0,yes,0,0,...,0,0,0,0,0,0,0,1,0,0
1,2.0,4.0,1.0,1.0,1.0,1.0,1.0,no,0,0,...,0,0,0,0,0,1,0,1,0,0
2,3.0,1.0,4.0,1.0,3.0,1.0,2.0,no,0,0,...,0,0,0,0,0,0,0,1,0,0
3,10.0,4.0,5.0,5.0,5.0,5.0,5.0,yes,0,0,...,0,0,0,0,0,0,1,1,0,0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no,0,0,...,0,0,0,0,0,0,1,1,0,0

In [ ]:
df['recommended'] = df['recommended'].map({'no':0,'yes':1})

In [ ]:
df.head()

,overall,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended,airline_Adria Airways,airline_Aegean Airlines,...,airline_Wizz Air,airline_airBaltic,airline_easyJet,airline_flydubai,traveller_type_Couple Leisure,traveller_type_Family Leisure,traveller_type_Solo Leisure,cabin_Economy Class,cabin_First Class,cabin_Premium Economy
0,7.0,4.0,5.0,4.0,4.0,2.0,4.0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1,2.0,4.0,1.0,1.0,1.0,1.0,1.0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
2,3.0,1.0,4.0,1.0,3.0,1.0,2.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,10.0,4.0,5.0,5.0,5.0,5.0,5.0,1,0,0,...,0,0,0,0,0,0,1,1,0,0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0,0,0,...,0,0,0,0,0,0,1,1,0,0

In [ ]:
# import pandas as pd
# final_df = pd.concat([df, x], axis=1)

In [ ]:
# final_df.head()

In [ ]:
# final_df.dropna(inplace=True)

In [ ]:
# final_df.shape

In [ ]:
# # prompt: i want to save final data

# import pandas as pd
# import nltk
# import re
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# from sklearn.feature_extraction.text import TfidfVectorizer
# import pickle

# # ... (Your existing code) ...

# final_df.to_csv('/content/drive/MyDrive/Colab Notebooks/final_data_new.csv', index=False)
# print("Final DataFrame saved to /content/drive/MyDrive/Colab Notebooks/final_data_.csv")

In [ ]:
x = df.drop(['recommended'], axis=1)
y = df['recommended']
y = y.astype(int)

In [ ]:
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import classification_report, confusion_matrix
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=25)

In [ ]:
model.score(x_test,y_test)

0.9597321198591912

In [ ]:
# import pickle
# with open('./.../model.pkl', 'wb') as f:
#     pickle.dump(model, f)

# print("./.../model.pkl")

In [ ]:
import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("model.pkl")

model.pkl

In [ ]:
import json
columns = {
    'data_columns' : [col.lower() for col in x.columns]
}
with open('columns.json', "w") as f:
  f.write(json.dumps(columns))

In [ ]:
# prompt: make function for pridction

import pickle
import numpy as np

def predict_recommendation(airline, traveller_type, cabin, overall, seat_comfort, cabin_service, food_bev, entertainment, ground_service, value_for_money):
    try:
        with open('model.pkl', 'rb') as f:
            model = pickle.load(f)

        # Load column names
        with open("columns.json", "r") as f:
            columns = json.load(f)

        x_cols = columns['data_columns']

        # Create input array
        X = np.zeros(len(x_cols))
        X[x_cols.index('overall')] = overall
        X[x_cols.index('seat_comfort')] = seat_comfort
        X[x_cols.index('cabin_service')] = cabin_service
        X[x_cols.index('food_bev')] = food_bev
        X[x_cols.index('entertainment')] = entertainment
        X[x_cols.index('ground_service')] = ground_service
        X[x_cols.index('value_for_money')] = value_for_money

        # Handle categorical features
        airline_col = 'airline_' + airline
        traveller_col = 'traveller_type_' + traveller_type
        cabin_col = 'cabin_' + cabin

        if airline_col in x_cols:
          X[x_cols.index(airline_col)] = 1
        if traveller_col in x_cols:
          X[x_cols.index(traveller_col)] = 1
        if cabin_col in x_cols:
          X[x_cols.index(cabin_col)] = 1

        # Make prediction
        prediction = model.predict([X])[0]
        return prediction

    except FileNotFoundError:
        print("Error: Model file not found.")
        return None
    except KeyError:
        print("Error: Invalid input features")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None
import json

In [ ]:
# prompt: wrire example for prediction

# Example usage of the prediction function
airline = "KLM"
traveller_type = "Business"
cabin = "Economy"
overall = 2
seat_comfort = 4
cabin_service = 4
food_bev = 4
entertainment = 4
ground_service = 5
value_for_money = 5

prediction = predict_recommendation(airline, traveller_type, cabin, overall, seat_comfort, cabin_service, food_bev, entertainment, ground_service, value_for_money)

print(f"Prediction: {prediction}")  # Output: 1 or 0

Prediction: 1

c:\Users\akhil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
# import numpy as np
# import re
# from nltk.stem import WordNetLemmatizer
# import pandas as pd  # Import pandas
# import pickle
# from nltk.corpus import stopwords # Import stopwords


# wnl = WordNetLemmatizer()


# def predict_recommendation(airline, traveller_type, cabin, seat_comfort, overall,
#                            cabin_service, food_bev, entertainment, ground_service,
#                            value_for_money, sms):
#     # Load the saved TF-IDF vectorizer
#     with open('/content/drive/MyDrive/Colab Notebooks/tfdai_data_new.pkl', 'rb') as f:
#         loaded_tfidf = pickle.load(f)

#     # Load the trained model
#     with open('/content/drive/MyDrive/Colab Notebooks/airline_review_model.pkl', 'rb') as f:
#         model = pickle.load(f)

#     # Preprocess the text message
#     message = re.sub(pattern='[^a-zA-Z]', repl=' ', string=sms)
#     message = message.lower()
#     words = message.split()  # Tokenizer
#     filtered_words = [word for word in words if word not in set(stopwords.words('english'))]
#     lemm_words = [wnl.lemmatize(word) for word in filtered_words]
#     message = ' '.join(lemm_words)

#     # Transform the text message using the trained TF-IDF vectorizer
#     temp = loaded_tfidf.transform([message]).toarray()

#     # Create the input feature vector X with the correct columns and a single row
#     X = pd.DataFrame(columns=x.columns, index=[0])  # Create with correct columns and single row
#     X.loc[0, ['overall', 'seat_comfort', 'cabin_service', 'food_bev',
#               'entertainment', 'ground_service', 'value_for_money']] = [
#         overall, seat_comfort, cabin_service, food_bev, entertainment,
#         ground_service, value_for_money
#     ]

#     # Set categorical features
#     # Get a list of all airline columns
#     airline_cols = [col for col in x.columns if col.startswith('airline_')]
#     # Set all airline columns to 0 initially
#     X[airline_cols] = 0
#     # Set the specific airline column to 1
#     if f'airline_{airline}' in airline_cols:
#         X.loc[0, f'airline_{airline}'] = 1


#     # Set Traveller Type
#     traveller_type_cols = [col for col in x.columns if col.startswith('traveller_type_')]
#     X[traveller_type_cols] = 0
#     if f'traveller_type_{traveller_type}' in traveller_type_cols:
#         X.loc[0, f'traveller_type_{traveller_type}'] = 1

#     # Set Cabin Type
#     cabin_cols = [col for col in x.columns if col.startswith('cabin_')]
#     X[cabin_cols] = 0
#     if f'cabin_{cabin}' in cabin_cols:
#         X.loc[0, f'cabin_{cabin}'] = 1


#     # Create a DataFrame for TF-IDF features and concatenate it with X
#     temp_df = pd.DataFrame(data=temp, columns=loaded_tfidf.get_feature_names_out(), index=[0])
#     X = pd.concat([X, temp_df], axis=1)

#     # Ensure all columns in X are in the same order as in x_train
#     X = X[x.columns]  # Reorder columns to match training data

#     return model.predict(X)[0]

In [ ]:
# predict_recommendation('Turkish Airlines','Family Leisure','Economy Class',3,8,4,4,4,4,3,"nice flight ever i have")

In [ ]:
# # prompt: write code for prediction and generate code also for preprocess data

# import re
# import numpy as np
# import pandas as pd
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer

# # ... (Your existing code for data preprocessing and model training) ...

# def preprocess_data(airline, traveller_type, cabin, seat_comfort, overall, cabin_service, food_bev, entertainment, ground_service, value_for_money, sms):
#     # Load the saved TF-IDF vectorizer
#     with open('/content/drive/MyDrive/Colab Notebooks/tfdai_data_new.pkl', 'rb') as f:
#         tfidf = pickle.load(f)

#     # Load the trained model
#     with open('/content/drive/MyDrive/Colab Notebooks/airline_review_model.pkl', 'rb') as f:
#         model = pickle.load(f)

#     wnl = WordNetLemmatizer()

#     # Preprocess the text message
#     message = re.sub(pattern='[^a-zA-Z]', repl=' ', string=sms)
#     message = message.lower()
#     words = message.split()
#     filtered_words = [word for word in words if word not in set(stopwords.words('english'))]
#     lemm_words = [wnl.lemmatize(word) for word in filtered_words]
#     message = ' '.join(lemm_words)

#     # Transform the text message using the trained TF-IDF vectorizer
#     temp = tfidf.transform([message]).toarray()

#     # Create an empty DataFrame with the same columns as the training data
#     X = pd.DataFrame(columns=x.columns, index=[0])  #Create DataFrame with index to add row of 0s
#     X.loc[0] = 0  #Add a row of 0s
#     # Assign values for numerical features
#     X.loc[0, 'overall'] = overall
#     X.loc[0, 'seat_comfort'] = seat_comfort
#     X.loc[0, 'cabin_service'] = cabin_service
#     X.loc[0, 'food_bev'] = food_bev
#     X.loc[0, 'entertainment'] = entertainment
#     X.loc[0, 'ground_service'] = ground_service
#     X.loc[0, 'value_for_money'] = value_for_money


#     # Get the column indices for the categorical features
#     loc_index_airline = np.where(x.columns == f'airline_{airline}')[0] # Fix: Use f-string for airline
#     loc_index_traveller = np.where(x.columns == f'traveller_type_{traveller_type}')[0]
#     loc_index_cabin = np.where(x.columns == f'cabin_{cabin}')[0]

#     # Assign values for categorical features using column indices
#     if loc_index_airline.size > 0:
#         X.iloc[0, loc_index_airline[0]] = 1
#     if loc_index_traveller.size > 0:
#         X.iloc[0, loc_index_traveller[0]] = 1
#     if loc_index_cabin.size > 0:
#         X.iloc[0, loc_index_cabin[0]] = 1

#     # Create a DataFrame for TF-IDF features and concatenate it with X
#     temp_df = pd.DataFrame(data=temp, columns=tfidf.get_feature_names_out(),index=[0])#Add index to concatenate
#     X = pd.concat([X, temp_df], axis=1)

#     # Ensure all columns in X are in the same order as in x_train, and only include columns present during training
#     X = X[x.columns.intersection(X.columns)] # Fix: Reorder and select columns

#     return X

# # Example usage of the preprocessor (replace with your actual values)
# airline = 'Turkish Airlines'
# traveller_type = 'Family Leisure'
# cabin = 'Economy Class'
# seat_comfort = 3
# overall = 8
# cabin_service = 4
# food_bev = 4
# entertainment = 4
# ground_service = 4
# value_for_money = 3
# sms = "nice flight ever i have"


# preprocessed_data = preprocess_data(airline, traveller_type, cabin, seat_comfort, overall, cabin_service, food_bev, entertainment, ground_service, value_for_money, sms)

# # Now you can use preprocessed_data with your model for prediction
# prediction = model.predict(preprocessed_data)[0]
# print(prediction)